# Cluster identity
k3s_cluster_name: k3s-dev

# Control plane VIP
k3s_vip: 10.0.3.20

# Network interface for kube-vip ARP
kubevip_iface: eth0

# kube-vip container version
kubevip_version: v1.0.4


# K3s install config
k3s_install_script: /tmp/k3s-install.sh
k3s_server_exec: "server --cluster-init"

# K3s filesystem paths
k3s_config_dir: /etc/rancher/k3s
k3s_manifests_dir: /var/lib/rancher/k3s/server/manifests
